myproject/core/urls.py
from django.conf.urls import url
from myproject.core.views import home


urlpatterns = [
    url(r'^$', home, name='home'),
]

myproject/crm/urls.py
from django.conf.urls import include, url
from myproject.crm import views as c


re_uuid = r'^(?P<uuid>' + \
    r'\b[0-9A-Fa-f]{8}\b(-\b[0-9A-Fa-f]{4}\b){3}-\b[0-9A-Fa-f]{12}\b)/'

company_patterns = [
    url(r'^$', c.CompanyList.as_view(), name='company_list'),
    url(r'^add/$', c.company_create, name='company_add'),
    url(
        regex=re_uuid + r'$',
        view=c.CompanyDetail.as_view(),
        name='company_detail'
    ),
    url(
        regex=re_uuid + r'edit/$',
        view=c.CompanyUpdate.as_view(),
        name='company_update'
    ),
    url(
        regex=re_uuid + r'delete/$',
        view=c.CompanyDelete.as_view(),
        name='company_delete'
    ),
]

person_patterns = [
    url(r'^$', c.PersonList.as_view(), name='person_list'),
    url(r'^add/$', c.person_create, name='person_add'),
    url(
        regex=re_uuid + r'$',
        view=c.PersonDetail.as_view(),
        name='person_detail'
    ),
    url(
        regex=re_uuid + r'edit/$',
        view=c.PersonUpdate.as_view(),
        name='person_update'
    ),
    url(
        regex=re_uuid + r'delete/$',
        view=c.PersonDelete.as_view(),
        name='person_delete'
    ),
]

status_patterns = [
    url(r'^$', c.StatusList.as_view(), name='status_list'),
    url(r'^add/$', c.status_create, name='status_add'),
    url(
        regex=re_uuid + r'$',
        view=c.StatusDetailView.as_view(),
        name='status_detail'
    ),
    url(
        regex=re_uuid + r'edit/$',
        view=c.StatusUpdate.as_view(),
        name='status_update'
    ),
    url(
        regex=re_uuid + r'delete/$',
        view=c.StatusDelete.as_view(),
        name='status_delete'
    ),
]

product_patterns = [
    url(r'^$', c.ProductList.as_view(), name='product_list'),
    url(r'^add/$', c.product_create, name='product_add'),
]


urlpatterns = [
    url(r'^company/', include(company_patterns)),
    url(r'^person/', include(person_patterns)),
    url(r'^status/', include(status_patterns)),
    url(r'^product/', include(product_patterns)),
]

myproject/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('myproject.core.urls', namespace='core')),
    url(r'^crm/', include('myproject.crm.urls', namespace='crm')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

myproject/crm/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import resolve_url as r
from django.utils.formats import number_format
from myproject.core.models import UUIDModel, TimeStampedModel
from .lists import STATUS


class Company(UUIDModel, TimeStampedModel):
    name = models.CharField('nome', max_length=50, unique=True)
    user = models.ForeignKey(
        User, verbose_name=u'usuário', related_name='company_user')

    class Meta:
        ordering = ['name']
        verbose_name = u'empresa'
        verbose_name_plural = u'empresas'

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return r('crm:company_detail', uuid=self.pk_uuid)


class Person(UUIDModel, TimeStampedModel):
    name = models.CharField('nome', max_length=50, unique=True)
    email = models.EmailField()
    phone = models.CharField('telefone', max_length=20, null=True, blank=True)
    user = models.ForeignKey(
        User, verbose_name=u'usuário', related_name='person_user')
    company = models.ForeignKey(
        'Company', verbose_name='empresa', related_name='person_company')

    class Meta:
        ordering = ['name']
        verbose_name = u'pessoa'
        verbose_name_plural = u'pessoas'

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return r('crm:person_detail', uuid=self.pk_uuid)


class Status(UUIDModel, TimeStampedModel):
    user = models.ForeignKey(
        User, verbose_name=u'usuário', related_name='status_user')
    company = models.ForeignKey(
        'Company', verbose_name='empresa', related_name='status_company')
    detail = models.CharField('detalhe', max_length=100, null=True, blank=True)
    next_contact = models.CharField(
        u'próximo contato', max_length=50, null=True, blank=True)
    status = models.CharField('tipo', max_length=2,
                              choices=STATUS, null=True, blank=True)

    class Meta:
        ordering = ['-created']
        verbose_name = u'status'
        verbose_name_plural = u'status'

    def __unicode__(self):
        return self.detail

    def get_absolute_url(self):
        return r('crm:status_detail', uuid=self.pk_uuid)


class Product(models.Model):
    product = models.CharField('Produto', max_length=100, unique=True)
    price = models.DecimalField('Preço', max_digits=7, decimal_places=2)

    class Meta:
        ordering = ['product']
        verbose_name = 'produto'
        verbose_name_plural = 'produtos'

    def __unicode__(self):
        return self.product

    def get_price(self):
        return "R$ %s" % number_format(self.price, 2)


class StatusDetail(models.Model):
    status = models.ForeignKey('Status', related_name='status_det')
    product = models.ForeignKey(
        Product, related_name='product_det', verbose_name='produto')
    quantity = models.PositiveSmallIntegerField('quantidade')
    price = models.DecimalField(
        u'Preço', max_digits=6, decimal_places=2, default=0)

    def __unicode__(self):
        return str(self.status)

    def get_subtotal(self):
        return self.price * (self.quantity or 0)

    subtotal = property(get_subtotal)

    def price_formated(self):
        return "R$ %s" % number_format(self.price, 2)

    def subtotal_formated(self):
        return "R$ %s" % number_format(self.subtotal, 2)

myproject/crm/forms.py
from django import forms
from .models import Company, Person, Status, Product


class CompanyForm(forms.ModelForm):

    class Meta:
        model = Company
        fields = '__all__'


class PersonForm(forms.ModelForm):

    class Meta:
        model = Person
        fields = '__all__'


class StatusForm(forms.ModelForm):

    class Meta:
        model = Status
        fields = '__all__'


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

myproject/crm/views.py
# -*- coding: utf-8 -*-
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .mixins import *
from .models import Company, Person, Product, StatusDetail
from .forms import CompanyForm, PersonForm, ProductForm


def company_create_form(request, form, template_name):
    data = {}
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            companies = Company.objects.all()
            data['html_company_list'] = render_to_string(
                'includes/partial_company_list.html',
                {'company_list': companies},
                request=request)
            data['is_form_valid'] = True
        else:
            data['is_form_valid'] = False

    context = {'form': form}
    data['html_form'] = render_to_string(
        template_name, context, request=request)
    return JsonResponse(data)


def company_create(request):
    if request.method == 'POST':
        form = CompanyForm(request.POST)
    else:
        form = CompanyForm()
    return company_create_form(request, form, 'crm/company_form.html')


class CompanyList(CounterMixin, SearchCompanyMixin, ListView):
    model = Company
    paginate_by = 10


class CompanyDetail(DetailView):
    model = Company
    slug_field = 'pk_uuid'
    slug_url_kwarg = 'uuid'


class CompanyUpdate(CompanyUpdateMixin, UpdateView):
    model = Company
    form_class = CompanyForm
    slug_field = 'pk_uuid'
    slug_url_kwarg = 'uuid'


class CompanyDelete(CompanyDeleteMixin, DeleteView):
    model = Company
    slug_field = 'pk_uuid'
    slug_url_kwarg = 'uuid'


def person_create_form(request, form, template_name):
    data = {}
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            persons = Person.objects.all()
            data['html_person_list'] = render_to_string(
                'includes/partial_person_list.html',
                {'person_list': persons},
                request=request)
            data['is_form_valid'] = True
        else:
            data['is_form_valid'] = False

    context = {'form': form}
    data['html_form'] = render_to_string(
        template_name, context, request=request)
    return JsonResponse(data)


def person_create(request):
    if request.method == 'POST':
        form = PersonForm(request.POST)
    else:
        form = PersonForm()
    return person_create_form(request, form, 'crm/person_form.html')


class PersonList(CounterMixin, SearchPersonMixin, ListView):
    model = Person
    paginate_by = 15


class PersonDetail(DetailView):
    model = Person
    slug_field = 'pk_uuid'
    slug_url_kwarg = 'uuid'


class PersonUpdate(PersonUpdateMixin, UpdateView):
    model = Person
    form_class = PersonForm
    slug_field = 'pk_uuid'
    slug_url_kwarg = 'uuid'


class PersonDelete(PersonDeleteMixin, DeleteView):
    model = Person
    slug_field = 'pk_uuid'
    slug_url_kwarg = 'uuid'


def status_create_form(request, form, template_name):
    data = {}
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            status = Status.objects.all()
            data['html_status_list'] = render_to_string(
                'includes/partial_status_list.html',
                {'status_list': status},
                request=request)
            data['is_form_valid'] = True
        else:
            data['is_form_valid'] = False

    context = {'form': form}
    data['html_form'] = render_to_string(
        template_name, context, request=request)
    return JsonResponse(data)


def status_create(request):
    if request.method == 'POST':
        form = StatusForm(request.POST)
    else:
        form = StatusForm()
    return status_create_form(request, form, 'crm/status_form.html')


class StatusList(CounterMixin, SearchStatusMixin, ListView):
    model = Status
    paginate_by = 15


class StatusDetailView(StatusDetailMixin, DetailView):
    model = Status
    slug_field = 'pk_uuid'
    slug_url_kwarg = 'uuid'


class StatusUpdate(StatusUpdateMixin, UpdateView):
    model = Status
    form_class = StatusForm
    slug_field = 'pk_uuid'
    slug_url_kwarg = 'uuid'


class StatusDelete(StatusDeleteMixin, DeleteView):
    model = Status
    slug_field = 'pk_uuid'
    slug_url_kwarg = 'uuid'


class ProductList(CounterMixin, SearchProductMixin, ListView):
    model = Product
    paginate_by = 20


product_create = CreateView.as_view(model=Product, form_class=ProductForm)

myproject/crm/templates/crm/company_delete.html
{% load bootstrap %}

<form class="js-company-update-form" action="{% url 'crm:company_delete' form.instance.pk_uuid %}" method="POST">
  <div class="modal-header">
    <button class="close" aria-label="Close" data-dismiss="modal" type="button">
      <span aria-hidden="True">&times;</span>
    </button>
    <h4 class="modal-title">Deletar Empresa</h4>
  </div> <!-- header -->

  <div class="modal-body">
    {% csrf_token %}

    <p class="lead">Tem certeza que dejesa deletar <strong>{{ empresa }}</strong>?</p>


  </div><!-- body -->

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    <button type="submit" class="btn btn-danger" >Delete</button>
  </div><!-- footer -->
</form>

myproject/crm/templates/crm/company_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}Company Detail{% endblock title %}

{% block content %}

<div class="row">
  {% include 'crm/company_detail_form.html' %}
</div>

<div class="row ">
  <!-- edit -->
  <button id="edit-company" type="button" class="btn btn-warning js-company-update"
          data-url="{% url 'crm:company_update' object.pk_uuid %}">
    <span class="fa fa-pencil"></span> Editar
  </button>

  <!-- delete with modal -->
  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">
    <span class="fa fa-times"></span> Deletar
  </button>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Confirmar</h4>
      </div>
        <form action="{% url 'crm:company_delete' object.pk_uuid %}" method="POST">
      <div class="modal-body">
          {% csrf_token %}
          Você quer deletar "{{ object }}"?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <input type="submit" class="btn btn-danger" value="Deletar" />
      </div>
        </form>
    </div>
  </div>
</div>

<!-- modal -->
<div id="modal-company" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content"></div>
  </div>
</div>


{% endblock content %}

{% block java_script %}
<script src="{% static 'js/apps.js' %}"></script>
{% endblock %}

myproject/crm/templates/crm/company_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}Empresas{% endblock title %}

{% block content %}

<form class="navbar-form navbar-right" action="" method="get">

    <button type="button" class="btn btn-primary js-create-company" data-url="{% url 'crm:company_add' %}">
        <span class="glyphicon glyphicon-plus"></span> Adicionar
    </button>

    <!-- search form -->
    <div class="form-group">
        <input id="search_box" name="search_box" type="text" placeholder="Search..." class="form-control">
        <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
    </div>
</form>

<h2>Lista de Empresas</h2>
<!-- o if company_list estava gerando o problema com atulizar o primeiro registro, por isso mudei -->
<table class="table table-striped" id="company-table">
    <thead>
    <tr>
        <th>Empresa</th>
        <th>Usuário</th>
        <th>Criado em</th>
    </tr>
    </thead>
    <tbody>

    {% include "includes/partial_company_list.html" %}
    </tbody>
</table>




<div>
    {% if count > 0 %}
    <hr>
    <h3>{{ company_list|length }} empresa{{ company_list|length|pluralize }}</h3>
    <h4><b>Total:</b> {{ page_obj.paginator.count }} empresa{{ page_obj.paginator.count|pluralize }}</h4>
    {% endif %}
</div>

<!-- modal -->
<div id="modal-company" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content"></div>
    </div>
</div>

{% endblock content %}

{% block java_script %}
<script src="{% static 'js/apps.js' %}"></script>
{% endblock %}

myproject/crm/templates/crm/company_update.html
{% load bootstrap %}

<form class="js-company-update-form" action="{% url 'crm:company_update' form.instance.pk_uuid %}" method="POST">
  <div class="modal-header">
    <button class="close" aria-label="Close" data-dismiss="modal" type="button">
      <span aria-hidden="True">&times;</span>
    </button>
    <h4 class="modal-title">Atualizar Empresa</h4>
  </div> <!-- header -->

  <div class="modal-body">
    {% csrf_token %}
    {{ form|bootstrap }}
  </div><!-- body -->

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    <button id="my-update" type="submit" class="btn btn-warning" >Alterar</button>
  </div><!-- footer -->
</form>

myproject/crm/templates/crm/person_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}Person Detail{% endblock title %}

{% block content %}

<div class="row">
  {% include 'crm/person_detail_form.html' %}
</div>

<div class="row ">
  <!-- edit -->
  <button id="edit-person" type="button" class="btn btn-warning js-person-update" data-url="{% url 'crm:person_update' person.pk_uuid %}">
    <span class="fa fa-pencil"></span> Editar
  </button>

  <!-- delete with modal -->
  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">
    <span class="fa fa-times"></span> Deletar
  </button>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Confirmar</h4>
      </div>
        <form action="{% url 'crm:person_delete' person.pk_uuid %}" method="POST">
      <div class="modal-body">
          {% csrf_token %}
          Você quer deletar "{{ object }}"?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <input type="submit" class="btn btn-danger" value="Deletar" />
      </div>
        </form>
    </div>
  </div>
</div>

<!-- modal -->
<div id="modal-person" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content"></div>
  </div>
</div>


{% endblock content %}

{% block java_script %}
<script src="{% static 'js/app_person.js' %}"></script>
{% endblock %}

myproject/crm/templates/crm/person_form.html
{% load bootstrap %}
<form class="js-person-create-form" action="{% url 'crm:person_add' %}" method="POST">
  <div class="modal-header">
    <button class="close" aria-label="Close" data-dismiss="modal" type="button">
      <span aria-hidden="True">&times;</span>
    </button>
    <h4 class="modal-title">Nova Pessoa</h4>
  </div> <!-- header -->

  <div class="modal-body">
    {% csrf_token %}
    {{ form|bootstrap }}
  </div><!-- body -->

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    <button type="submit" class="btn btn-primary" >Salvar</button>
  </div><!-- footer -->
</form>

myproject/crm/templates/crm/person_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}Pessoas{% endblock title %}

{% block content %}

<form class="navbar-form navbar-right" action="" method="get">

  <button type="button" class="btn btn-primary js-create-person" data-url="{% url 'crm:person_add' %}">
    <span class="glyphicon glyphicon-plus"></span> Adicionar
  </button>

  <!-- search form -->
  <div class="form-group">
    <input id="search_box" name="search_box" type="text" placeholder="Search..." class="form-control">
    <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
  </div>
</form>

<h2>Lista de Pessoas</h2>

{% if person_list %}
  <table class="table table-striped" id="person-table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>E-mail</th>
        <th>Telefone</th>
        <th>Criado por</th>
        <th>Empresa</th>
        <th>Criado em</th>
      </tr>
    </thead>
    <tbody>
      {% include "includes/partial_person_list.html" %}
    </tbody>
  </table>
{% else %}
  <div class="alert alert-warning text-center">
    <p>Sem itens na lista.</p>
  </div>
{% endif %}

<div>
  {% if count > 0 %}
    <hr>
    <h3>{{ person_list|length }} pessoa{{ person_list|length|pluralize }}</h3>
    <h4><b>Total:</b> {{ page_obj.paginator.count }} pessoa{{ page_obj.paginator.count|pluralize }}</h4>
  {% endif %}
</div>

<!-- modal -->
<div id="modal-person" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content"></div>
  </div>
</div>

{% endblock content %}

{% block java_script %}
<script src="{% static 'js/app_person.js' %}"></script>
{% endblock %}

myproject/crm/templates/crm/person_update.html
{% load bootstrap %}

<form class="js-person-update-form" action="{% url 'crm:person_update' form.instance.pk_uuid %}" method="POST">
  <div class="modal-header">
    <button class="close" aria-label="Close" data-dismiss="modal" type="button">
      <span aria-hidden="True">&times;</span>
    </button>
    <h4 class="modal-title">Atualizar Pessoa</h4>
  </div> <!-- header -->

  <div class="modal-body">
    {% csrf_token %}
    {{ form|bootstrap }}
  </div><!-- body -->

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    <button id="my-update" type="submit" class="btn btn-warning" >Alterar</button>
  </div><!-- footer -->
</form>

myproject/crm/templates/crm/status_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}Status Detail{% endblock title %}

{% block content %}

<div class="row">
  {% include 'crm/status_detail_form.html' %}
</div>

<div class="row ">
  <!-- edit -->
  <button id="edit-status" type="button" class="btn btn-warning js-status-update" data-url="{% url 'crm:status_update' status.pk_uuid %}">
    <span class="fa fa-pencil"></span> Editar
  </button>

  <!-- delete with modal -->
  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">
    <span class="fa fa-times"></span> Deletar
  </button>
</div>

<div>
  <table class="table">
    <thead>
      <tr>
        <th>Produto</th>
        <th class="text-center">Quantidade</th>
        <th class="text-right">Preço</th>
        <th class="text-right">Subtotal</th>
      </tr>
    </thead>
    <tbody>
    {% for item in itens %}
      <tr>
        <td>{{ item.product.product }}</a></td>
        <td class="text-center">{{ item.quantity }}</td>
        <td class="text-right">{{ item.price_formated }}</td>
        <td class="text-right">{{ item.subtotal_formated }}</td>
      </tr>
    {% empty %}
      <p>Sem itens na lista.</p>
    {% endfor %}
    </tbody>
  </table>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Confirmar</h4>
      </div>
        <form action="{% url 'crm:status_delete' status.pk_uuid %}" method="POST">
      <div class="modal-body">
          {% csrf_token %}
          Você quer deletar "{{ object }}"?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <input type="submit" class="btn btn-danger" value="Deletar" />
      </div>
        </form>
    </div>
  </div>
</div>

<!-- modal -->
<div id="modal-status" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content"></div>
  </div>
</div>


{% endblock content %}

{% block java_script %}
<script src="{% static 'js/app_status.js' %}"></script>
{% endblock %}

myproject/crm/templates/crm/status_detail_form.html
<div id="detail-status">
  <ul class="breadcrumb">
    <li><a href="{% url 'core:home' %}">Home</a> <span class="divider"></span></li>
    <li><a href="{% url 'crm:status_list' %}">Status</a> <span class="divider"></span></li>
    <li class="active">{{ object.pk_uuid }}</li>
  </ul>

  <div class="col-lg-8">
    <div class="col-md-offset-3 column">
      <h1>{{ object.detail }}</h1>
    </div>

    </br>

    <table class="table table-user-information">
      <tbody>
        <tr>
          <th class="col-md-3 text-right">Status</th>
          <td>{{ object.get_status_display }}</td>
        </tr>
        <tr>
          <th class="col-md-3 text-right">Próximo contato</th>
          <td>{{ object.next_contact }}</td>
        </tr>
        <tr>
          <th class="col-md-3 text-right">Empresa</th>
          <td>{{ object.company }}</td>
        </tr>
        <tr>
          <th class="col-md-3 text-right">Criado por</th>
          <td>{{ object.user }}</td>
        </tr>
        <tr>
          <th class="col-md-3 text-right">Criado em</th>
          <td>{{ object.created|date:"d/m/Y" }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

myproject/crm/templates/crm/status_form.html
{% load bootstrap %}
<form class="js-status-create-form" action="{% url 'crm:status_add' %}" method="POST">
  <div class="modal-header">
    <button class="close" aria-label="Close" data-dismiss="modal" type="button">
      <span aria-hidden="True">&times;</span>
    </button>
    <h4 class="modal-title">Novo Status</h4>
  </div> <!-- header -->

  <div class="modal-body">
    {% csrf_token %}
    {{ form|bootstrap }}
  </div><!-- body -->

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    <button type="submit" class="btn btn-primary" >Salvar</button>
  </div><!-- footer -->
</form>

myproject/crm/templates/crm/status_list.html
  {% extends "base.html" %}
{% load static %}
{% block title %}Status{% endblock title %}

{% block content %}

<form class="navbar-form navbar-right" action="" method="get">

  <button type="button" class="btn btn-primary js-create-status" data-url="{% url 'crm:status_add' %}">
    <span class="glyphicon glyphicon-plus"></span> Adicionar
  </button>

  <!-- search form -->
  <div class="form-group">
    <input id="search_box" name="search_box" type="text" placeholder="Search..." class="form-control">
    <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
  </div>
</form>

<h2>Lista de Status</h2>

{% if status_list %}
  <table class="table table-striped" id="status-table">
    <thead>
      <tr>
        <th>Detalhes</th>
        <th>Próximo contato</th>
        <th>Status</th>
        <th>Criado por</th>
        <th>Empresa</th>
        <th>Criado em</th>
      </tr>
    </thead>
    <tbody>
      {% include "includes/partial_status_list.html" %}
    </tbody>
  </table>
{% else %}
  <div class="alert alert-warning text-center">
    <p>Sem itens na lista.</p>
  </div>
{% endif %}

<div>
  {% if count > 0 %}
    <hr>
    <h3>{{ status_list|length }} pessoa{{ status_list|length|pluralize }}</h3>
    <h4><b>Total:</b> {{ page_obj.paginator.count }} pessoa{{ page_obj.paginator.count|pluralize }}</h4>
  {% endif %}
</div>

<!-- modal -->
<div id="modal-status" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content"></div>
  </div>
</div>

{% endblock content %}

{% block java_script %}
<script src="{% static 'js/app_status.js' %}"></script>
{% endblock %}

myproject/crm/templates/crm/status_update.html
{% load bootstrap %}

<form class="js-status-update-form" action="{% url 'crm:status_update' form.instance.pk_uuid %}" method="POST">
  <div class="modal-header">
    <button class="close" aria-label="Close" data-dismiss="modal" type="button">
      <span aria-hidden="True">&times;</span>
    </button>
    <h4 class="modal-title">Atualizar Status</h4>
  </div> <!-- header -->

  <div class="modal-body">
    {% csrf_token %}
    {{ form|bootstrap }}
  </div><!-- body -->

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    <button id="my-update" type="submit" class="btn btn-warning" >Alterar</button>
  </div><!-- footer -->
</form>