myproject/core/urls.py
from django.conf.urls import url
from myproject.core.views import home


urlpatterns = [
    url(r'^$', home, name='home'),
]

myproject/crm/urls.py
from django.conf.urls import include, url
from myproject.crm import views as c


re_uuid = r'^(?P<uuid>' + \
    r'\b[0-9A-Fa-f]{8}\b(-\b[0-9A-Fa-f]{4}\b){3}-\b[0-9A-Fa-f]{12}\b)/'

company_patterns = [
    url(r'^$', c.CompanyList.as_view(), name='company_list'),
    url(r'^add/$', c.company_create, name='company_add'),
    url(
        regex=re_uuid + r'$',
        view=c.CompanyDetail.as_view(),
        name='company_detail'
    ),
    url(
        regex=re_uuid + r'edit/$',
        view=c.CompanyUpdate.as_view(),
        name='company_update'
    ),
    url(
        regex=re_uuid + r'delete/$',
        view=c.CompanyDelete.as_view(),
        name='company_delete'
    ),
]

person_patterns = [
    url(r'^$', c.PersonList.as_view(), name='person_list'),
    url(r'^add/$', c.person_create, name='person_add'),
    url(
        regex=re_uuid + r'$',
        view=c.PersonDetail.as_view(),
        name='person_detail'
    ),
    url(
        regex=re_uuid + r'edit/$',
        view=c.PersonUpdate.as_view(),
        name='person_update'
    ),
    url(
        regex=re_uuid + r'delete/$',
        view=c.PersonDelete.as_view(),
        name='person_delete'
    ),
]

status_patterns = [
    url(r'^$', c.StatusList.as_view(), name='status_list'),
    url(r'^add/$', c.status_create, name='status_add'),
    url(
        regex=re_uuid + r'$',
        view=c.StatusDetailView.as_view(),
        name='status_detail'
    ),
    url(
        regex=re_uuid + r'edit/$',
        view=c.StatusUpdate.as_view(),
        name='status_update'
    ),
    url(
        regex=re_uuid + r'delete/$',
        view=c.StatusDelete.as_view(),
        name='status_delete'
    ),
]

product_patterns = [
    url(r'^$', c.ProductList.as_view(), name='product_list'),
    url(r'^add/$', c.product_create, name='product_add'),
]


urlpatterns = [
    url(r'^company/', include(company_patterns)),
    url(r'^person/', include(person_patterns)),
    url(r'^status/', include(status_patterns)),
    url(r'^product/', include(product_patterns)),
]

myproject/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('myproject.core.urls', namespace='core')),
    url(r'^crm/', include('myproject.crm.urls', namespace='crm')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

myproject/core/models.py
# -*- coding: utf-8 -*-
import uuid
from django.db import models
from localflavor.br.br_states import STATE_CHOICES


class UUIDModel(models.Model):
    # Gera um uuid de 32 caracteres
    pk_uuid = models.UUIDField(
        editable=False, unique=True, db_index=True, default=uuid.uuid4)

    class Meta:
        abstract = True


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em', auto_now_add=True, auto_now=False)
    modified = models.DateTimeField(
        'modificado em', auto_now_add=False, auto_now=True)

    class Meta:
        abstract = True


class Address(models.Model):
    address = models.CharField(u'endereço', max_length=100, blank=True)
    complement = models.CharField('complemento', max_length=100, blank=True)
    district = models.CharField('bairro', max_length=100, blank=True)
    city = models.CharField('cidade', max_length=100, blank=True)
    uf = models.CharField('UF', max_length=2,
                          choices=STATE_CHOICES, blank=True)
    cep = models.CharField('CEP', max_length=9, blank=True)

    class Meta:
        abstract = True

myproject/core/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render


def home(request):
    return render(request, 'index.html')

myproject/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">

    <title>{% block title %}Django{% endblock title %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Font Awesome core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <!-- Bootstrap core JS -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body>

  {% include "nav.html" %}

  <div id="wrap">
    <div class="container">
      {% block content %}{% endblock content %}
    </div>
  </div>

  {% block java_script %}
  {% endblock %}

  </body>
</html>

myproject/core/templates/index.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <div class="jumbotron">
      <h1>Bem-vindo!</h1>
    </div>
  </div>
{% endblock content %}

myproject/core/templates/nav.html
<!-- Menu -->
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="current"><a href="{% url 'core:home' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
        <li><a href="{% url 'crm:company_list' %}">Empresas</a></li>
        <li><a href="{% url 'crm:person_list' %}">Pessoas</a></li>
        <li><a href="{% url 'crm:status_list' %}">Status</a></li>
        <li><a href="{% url 'crm:product_list' %}">Produtos</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'admin:index' %}">Admin</a></li>
      </ul>
    </div>
  </div>
</div>